# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    Linux:
      vmImage: ubuntu-16.04
    macOS:
      vmImage: macOS-10.13
    Windows:
      vmImage: vs2017-win2016

pool:
  vmImage: $(vmImage)

steps:
- script: 
    npm install
    npm run build
  displayName: 'npm install and build'
- script: echo Puto el que lo lea!

